name: Dendron

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source ğŸ›ï¸
      uses: actions/checkout@v2.3.1
      with:
        persist-credential: false

    # Retain Node modules across builds
    - name: Restore Node modules cache â›“
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: |
          node_modules
          .next/node_modules
        key: node-modules-${{ hashFiles('yarn.lock')}}

    - name: Install npm dependencies ğŸ‘¾
      run: yarn

    - name: Initialize or pull nextjs template ğŸ‘¨â€ğŸ’»
      run: "(test -d .next) && (echo 'updating dendron next...' && cd .next && git reset --hard && git clean -f && git pull && yarn && cd ..) || (echo 'init dendron next' && npx dendron publish init)"

    - name: Delete next cache ğŸ’½
      run: "(test -d .next/.next) && (rm -rf .next/.next && echo 'delete Next.js cache') || echo 'no Next.js cache found'"

    - name: Export notes ğŸ“š
      run: npx dendron publish export --target github --yes

    - name: Deploy site âœ¨
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true